parameters:
#    booksmart_metrics_nbs.example.class: Booksmart\Metrics\NBSBundle\Example

services:
#    booksmart_metrics_nbs.example:
#        class: %booksmart_metrics_nbs.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
