Booksmart\Metrics\SoundcloudBundle\Entity\Search:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        query:
            type: string
            length: '255'
    lifecycleCallbacks: {  }

    oneToMany:
        results:
            targetEntity: Track
            mappedBy: search

    oneToMany:
        artistResults:
            targetEntity: Booksmart\Metrics\EchonestBundle\Entity\Artist
            mappedBy: artistSearch
