Booksmart\Metrics\EchonestBundle\Entity\Genre:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'

    oneToMany:
        artists:
            targetEntity: Artist
            mappedBy: genre
    manToMany:
        searches:
            targetEntity: Booksmart\Metrics\SoundcloudBundle\Entity\Search
            mappedBy: genres
    lifecycleCallbacks: {  }
